name: quantization-adalora-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    # base
    - torch==2.10.0
    - torchcodec==0.10.0

    # model and training
    - transformers
    - accelerate
    - datasets
    - peft
    - jiwer
    - bitsandbytes

    # cpu eval + quantization
    - optimum[onnxruntime]
    - onnx
    - onnxruntime
    - onnx-ir

    # dep
    - numpy
    - python-dotenv
    - evaluate